# -*- coding: utf-8 -*-
"""Cópia de mes-10-dia-26-mat236.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1_t0O2O40VED1rNoV25GS4Bne_CYwMI
"""

remotes::install_github("gilberto-sassi/statBasics")
library(statBasics)
library(tidyverse)

n <- 100
num_amostra <- 1000
media_pop <- 10
calculos <- seq_len(num_amostra) |>
  map_dbl(\(k) {
    amostra <- rnorm(n, mean = media_pop, sd = 2)
    (mean(amostra)  - media_pop) * sqrt(n) / sd(amostra)
  })
calculos

"""# interepretação do intervalo de confinaça 

## Intervalo de confinaça t 

população: N(10, 2)

* Construir intervalo de confiança quando **NÃO CONHECEMOS O DESVIO PADRÃO DA POPULAÇÃO.**
* coeficiente de confiança: 97%
"""

num_amostras <- 1000
n <- 13
media_pop <- 10
dp_pop <- 2
intervalos_corretos <- seq_len(num_amostras) |>
  map_dbl(\(k) {
    amostra <- rnorm(n, mean = media_pop, sd = dp_pop)
    quantil <- qt(0.985, df = n - 1)
    li <- mean(amostra) - quantil * sd(amostra) / sqrt(n)
    ls <- mean(amostra) + quantil * sd(amostra) / sqrt(n)
    return(li <= media_pop & media_pop <= ls)
  })

intervalos_corretos
mean(intervalos_corretos)

amostra <- rnorm(20, mean = 10, sd = 4)

ci_norm(amostra, conf_level = 0.96)